"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var numeros_diamantes_1 = require("./numeros_diamantes");
var fooDosDiamantes = numeros_diamantes_1.DosD("");
console.log(fooDosDiamantes);
var fooTresDiamante = numeros_diamantes_1.TresD("");
console.log(fooTresDiamante);
var fooCuatroDiamante = numeros_diamantes_1.CuatroD("");
console.log(fooCuatroDiamante);
var fooCincoDiamante = numeros_diamantes_1.CincoD("");
console.log(fooCincoDiamante);
var fooSeisDiamante = numeros_diamantes_1.SeisD("");
console.log(fooSeisDiamante);
var fooSieteDiamante = numeros_diamantes_1.SieteD("");
console.log(fooSieteDiamante);
var fooOchoDiamante = numeros_diamantes_1.OchoD("");
console.log(fooOchoDiamante);
var fooNueveDiamante = numeros_diamantes_1.NueveD("");
console.log(fooNueveDiamante);
var fooDiezDiamante = numeros_diamantes_1.DiezD("");
console.log(fooDiezDiamante);
var fooJotaDiamante = numeros_diamantes_1.JotaD("");
console.log(fooJotaDiamante);
var fooQuuDiamante = numeros_diamantes_1.QuuD("");
console.log(fooQuuDiamante);
var fooKaaDiamante = numeros_diamantes_1.kaaD("");
console.log(fooKaaDiamante);
var fooAsDiamante = numeros_diamantes_1.AsD("");
console.log(fooAsDiamante);
