"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var numeros_trebol_1 = require("./numeros_trebol");
var fooDos = numeros_trebol_1.Dos("");
console.log(fooDos);
var fooTres = numeros_trebol_1.Tres("");
console.log(fooTres);
var fooCuatro = numeros_trebol_1.Cuatro("");
console.log(fooCuatro);
var fooCinco = numeros_trebol_1.Cinco("");
console.log(fooCinco);
var fooSeis = numeros_trebol_1.Seis("");
console.log(fooSeis);
var fooSiete = numeros_trebol_1.Siete("");
console.log(fooSiete);
var fooOcho = numeros_trebol_1.Ocho("");
console.log(fooOcho);
var fooNueve = numeros_trebol_1.Nueve("");
console.log(fooNueve);
var fooDiez = numeros_trebol_1.Diez("");
console.log(fooDiez);
var fooJota = numeros_trebol_1.Jota("");
console.log(fooJota);
var fooQuu = numeros_trebol_1.Quu("");
console.log(fooQuu);
var fooKaa = numeros_trebol_1.kaa("");
console.log(fooKaa);
var fooAs = numeros_trebol_1.As("");
console.log(fooAs);
