"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var numeros_c_negro_1 = require("./numeros_c_negro");
var fooDosCorazonNegro = numeros_c_negro_1.DosCN("");
console.log(fooDosCorazonNegro);
var fooTresCorazonNegro = numeros_c_negro_1.TresCN("");
console.log(fooTresCorazonNegro);
var fooCuatroCorazonNegro = numeros_c_negro_1.CuatroCN("");
console.log(fooCuatroCorazonNegro);
var fooCincoCorazonNegro = numeros_c_negro_1.CincoCN("");
console.log(fooCincoCorazonNegro);
var fooSeisCorazonNegro = numeros_c_negro_1.SeisCN("");
console.log(fooSeisCorazonNegro);
var fooSieteCorazonNegro = numeros_c_negro_1.SieteCN("");
console.log(fooSieteCorazonNegro);
var fooOchoCorazonNegro = numeros_c_negro_1.OchoCN("");
console.log(fooOchoCorazonNegro);
var fooNueveCorazonNegro = numeros_c_negro_1.NueveCN("");
console.log(fooNueveCorazonNegro);
var fooDiezCorazonNegro = numeros_c_negro_1.DiezCN("");
console.log(fooDiezCorazonNegro);
var fooJotaCorazonNegro = numeros_c_negro_1.JotaCN("");
console.log(fooJotaCorazonNegro);
var fooQuuCorazonNegro = numeros_c_negro_1.QuuCN("");
console.log(fooQuuCorazonNegro);
var fooKaaCorazonNegro = numeros_c_negro_1.kaaCN("");
console.log(fooKaaCorazonNegro);
var fooAsCorazonNegro = numeros_c_negro_1.AsCN("");
console.log(fooAsCorazonNegro);
