"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var numeros_corazon_1 = require("./numeros_corazon");
var fooDosCorazon = numeros_corazon_1.DosC("");
console.log(fooDosCorazon);
var fooTresCorazones = numeros_corazon_1.TresC("");
console.log(fooTresCorazones);
var fooCuatroCorazones = numeros_corazon_1.CuatroC("");
console.log(fooCuatroCorazones);
var fooCincoCorazones = numeros_corazon_1.CincoC("");
console.log(fooCincoCorazones);
var fooSeisCorazones = numeros_corazon_1.SeisC("");
console.log(fooSeisCorazones);
var fooSieteCorazones = numeros_corazon_1.SieteC("");
console.log(fooSieteCorazones);
var fooOchoCorazones = numeros_corazon_1.OchoC("");
console.log(fooOchoCorazones);
var fooNueveCorazones = numeros_corazon_1.NueveC("");
console.log(fooNueveCorazones);
var fooDiezCorazones = numeros_corazon_1.DiezC("");
console.log(fooDiezCorazones);
var fooJotaCorazones = numeros_corazon_1.JotaC("");
console.log(fooJotaCorazones);
var fooQuuCorazones = numeros_corazon_1.QuuC("");
console.log(fooQuuCorazones);
var fooKaaCorazones = numeros_corazon_1.kaaC("");
console.log(fooKaaCorazones);
var fooAsCorazones = numeros_corazon_1.AsC("");
console.log(fooAsCorazones);
